require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ObjectiveScoresController do

  # This should return the minimal set of attributes required to create a valid
  # ObjectiveScore. As you add validations to ObjectiveScore, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ObjectiveScoresController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all objective_scores as @objective_scores" do
      objective_score = ObjectiveScore.create! valid_attributes
      get :index, {}, valid_session
      assigns(:objective_scores).should eq([objective_score])
    end
  end

  describe "GET show" do
    it "assigns the requested objective_score as @objective_score" do
      objective_score = ObjectiveScore.create! valid_attributes
      get :show, {:id => objective_score.to_param}, valid_session
      assigns(:objective_score).should eq(objective_score)
    end
  end

  describe "GET new" do
    it "assigns a new objective_score as @objective_score" do
      get :new, {}, valid_session
      assigns(:objective_score).should be_a_new(ObjectiveScore)
    end
  end

  describe "GET edit" do
    it "assigns the requested objective_score as @objective_score" do
      objective_score = ObjectiveScore.create! valid_attributes
      get :edit, {:id => objective_score.to_param}, valid_session
      assigns(:objective_score).should eq(objective_score)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ObjectiveScore" do
        expect {
          post :create, {:objective_score => valid_attributes}, valid_session
        }.to change(ObjectiveScore, :count).by(1)
      end

      it "assigns a newly created objective_score as @objective_score" do
        post :create, {:objective_score => valid_attributes}, valid_session
        assigns(:objective_score).should be_a(ObjectiveScore)
        assigns(:objective_score).should be_persisted
      end

      it "redirects to the created objective_score" do
        post :create, {:objective_score => valid_attributes}, valid_session
        response.should redirect_to(ObjectiveScore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved objective_score as @objective_score" do
        # Trigger the behavior that occurs when invalid params are submitted
        ObjectiveScore.any_instance.stub(:save).and_return(false)
        post :create, {:objective_score => {}}, valid_session
        assigns(:objective_score).should be_a_new(ObjectiveScore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ObjectiveScore.any_instance.stub(:save).and_return(false)
        post :create, {:objective_score => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested objective_score" do
        objective_score = ObjectiveScore.create! valid_attributes
        # Assuming there are no other objective_scores in the database, this
        # specifies that the ObjectiveScore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ObjectiveScore.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => objective_score.to_param, :objective_score => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested objective_score as @objective_score" do
        objective_score = ObjectiveScore.create! valid_attributes
        put :update, {:id => objective_score.to_param, :objective_score => valid_attributes}, valid_session
        assigns(:objective_score).should eq(objective_score)
      end

      it "redirects to the objective_score" do
        objective_score = ObjectiveScore.create! valid_attributes
        put :update, {:id => objective_score.to_param, :objective_score => valid_attributes}, valid_session
        response.should redirect_to(objective_score)
      end
    end

    describe "with invalid params" do
      it "assigns the objective_score as @objective_score" do
        objective_score = ObjectiveScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ObjectiveScore.any_instance.stub(:save).and_return(false)
        put :update, {:id => objective_score.to_param, :objective_score => {}}, valid_session
        assigns(:objective_score).should eq(objective_score)
      end

      it "re-renders the 'edit' template" do
        objective_score = ObjectiveScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ObjectiveScore.any_instance.stub(:save).and_return(false)
        put :update, {:id => objective_score.to_param, :objective_score => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested objective_score" do
      objective_score = ObjectiveScore.create! valid_attributes
      expect {
        delete :destroy, {:id => objective_score.to_param}, valid_session
      }.to change(ObjectiveScore, :count).by(-1)
    end

    it "redirects to the objective_scores list" do
      objective_score = ObjectiveScore.create! valid_attributes
      delete :destroy, {:id => objective_score.to_param}, valid_session
      response.should redirect_to(objective_scores_url)
    end
  end

end
