require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PerspectivesController do

  # This should return the minimal set of attributes required to create a valid
  # Perspective. As you add validations to Perspective, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PerspectivesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all perspectives as @perspectives" do
      perspective = Perspective.create! valid_attributes
      get :index, {}, valid_session
      assigns(:perspectives).should eq([perspective])
    end
  end

  describe "GET show" do
    it "assigns the requested perspective as @perspective" do
      perspective = Perspective.create! valid_attributes
      get :show, {:id => perspective.to_param}, valid_session
      assigns(:perspective).should eq(perspective)
    end
  end

  describe "GET new" do
    it "assigns a new perspective as @perspective" do
      get :new, {}, valid_session
      assigns(:perspective).should be_a_new(Perspective)
    end
  end

  describe "GET edit" do
    it "assigns the requested perspective as @perspective" do
      perspective = Perspective.create! valid_attributes
      get :edit, {:id => perspective.to_param}, valid_session
      assigns(:perspective).should eq(perspective)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Perspective" do
        expect {
          post :create, {:perspective => valid_attributes}, valid_session
        }.to change(Perspective, :count).by(1)
      end

      it "assigns a newly created perspective as @perspective" do
        post :create, {:perspective => valid_attributes}, valid_session
        assigns(:perspective).should be_a(Perspective)
        assigns(:perspective).should be_persisted
      end

      it "redirects to the created perspective" do
        post :create, {:perspective => valid_attributes}, valid_session
        response.should redirect_to(Perspective.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved perspective as @perspective" do
        # Trigger the behavior that occurs when invalid params are submitted
        Perspective.any_instance.stub(:save).and_return(false)
        post :create, {:perspective => {}}, valid_session
        assigns(:perspective).should be_a_new(Perspective)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Perspective.any_instance.stub(:save).and_return(false)
        post :create, {:perspective => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested perspective" do
        perspective = Perspective.create! valid_attributes
        # Assuming there are no other perspectives in the database, this
        # specifies that the Perspective created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Perspective.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => perspective.to_param, :perspective => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested perspective as @perspective" do
        perspective = Perspective.create! valid_attributes
        put :update, {:id => perspective.to_param, :perspective => valid_attributes}, valid_session
        assigns(:perspective).should eq(perspective)
      end

      it "redirects to the perspective" do
        perspective = Perspective.create! valid_attributes
        put :update, {:id => perspective.to_param, :perspective => valid_attributes}, valid_session
        response.should redirect_to(perspective)
      end
    end

    describe "with invalid params" do
      it "assigns the perspective as @perspective" do
        perspective = Perspective.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Perspective.any_instance.stub(:save).and_return(false)
        put :update, {:id => perspective.to_param, :perspective => {}}, valid_session
        assigns(:perspective).should eq(perspective)
      end

      it "re-renders the 'edit' template" do
        perspective = Perspective.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Perspective.any_instance.stub(:save).and_return(false)
        put :update, {:id => perspective.to_param, :perspective => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested perspective" do
      perspective = Perspective.create! valid_attributes
      expect {
        delete :destroy, {:id => perspective.to_param}, valid_session
      }.to change(Perspective, :count).by(-1)
    end

    it "redirects to the perspectives list" do
      perspective = Perspective.create! valid_attributes
      delete :destroy, {:id => perspective.to_param}, valid_session
      response.should redirect_to(perspectives_url)
    end
  end

end
