require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RawDataScoresController do

  # This should return the minimal set of attributes required to create a valid
  # RawDataScore. As you add validations to RawDataScore, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RawDataScoresController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all raw_data_scores as @raw_data_scores" do
      raw_data_score = RawDataScore.create! valid_attributes
      get :index, {}, valid_session
      assigns(:raw_data_scores).should eq([raw_data_score])
    end
  end

  describe "GET show" do
    it "assigns the requested raw_data_score as @raw_data_score" do
      raw_data_score = RawDataScore.create! valid_attributes
      get :show, {:id => raw_data_score.to_param}, valid_session
      assigns(:raw_data_score).should eq(raw_data_score)
    end
  end

  describe "GET new" do
    it "assigns a new raw_data_score as @raw_data_score" do
      get :new, {}, valid_session
      assigns(:raw_data_score).should be_a_new(RawDataScore)
    end
  end

  describe "GET edit" do
    it "assigns the requested raw_data_score as @raw_data_score" do
      raw_data_score = RawDataScore.create! valid_attributes
      get :edit, {:id => raw_data_score.to_param}, valid_session
      assigns(:raw_data_score).should eq(raw_data_score)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RawDataScore" do
        expect {
          post :create, {:raw_data_score => valid_attributes}, valid_session
        }.to change(RawDataScore, :count).by(1)
      end

      it "assigns a newly created raw_data_score as @raw_data_score" do
        post :create, {:raw_data_score => valid_attributes}, valid_session
        assigns(:raw_data_score).should be_a(RawDataScore)
        assigns(:raw_data_score).should be_persisted
      end

      it "redirects to the created raw_data_score" do
        post :create, {:raw_data_score => valid_attributes}, valid_session
        response.should redirect_to(RawDataScore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved raw_data_score as @raw_data_score" do
        # Trigger the behavior that occurs when invalid params are submitted
        RawDataScore.any_instance.stub(:save).and_return(false)
        post :create, {:raw_data_score => {}}, valid_session
        assigns(:raw_data_score).should be_a_new(RawDataScore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RawDataScore.any_instance.stub(:save).and_return(false)
        post :create, {:raw_data_score => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested raw_data_score" do
        raw_data_score = RawDataScore.create! valid_attributes
        # Assuming there are no other raw_data_scores in the database, this
        # specifies that the RawDataScore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RawDataScore.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => raw_data_score.to_param, :raw_data_score => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested raw_data_score as @raw_data_score" do
        raw_data_score = RawDataScore.create! valid_attributes
        put :update, {:id => raw_data_score.to_param, :raw_data_score => valid_attributes}, valid_session
        assigns(:raw_data_score).should eq(raw_data_score)
      end

      it "redirects to the raw_data_score" do
        raw_data_score = RawDataScore.create! valid_attributes
        put :update, {:id => raw_data_score.to_param, :raw_data_score => valid_attributes}, valid_session
        response.should redirect_to(raw_data_score)
      end
    end

    describe "with invalid params" do
      it "assigns the raw_data_score as @raw_data_score" do
        raw_data_score = RawDataScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RawDataScore.any_instance.stub(:save).and_return(false)
        put :update, {:id => raw_data_score.to_param, :raw_data_score => {}}, valid_session
        assigns(:raw_data_score).should eq(raw_data_score)
      end

      it "re-renders the 'edit' template" do
        raw_data_score = RawDataScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RawDataScore.any_instance.stub(:save).and_return(false)
        put :update, {:id => raw_data_score.to_param, :raw_data_score => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested raw_data_score" do
      raw_data_score = RawDataScore.create! valid_attributes
      expect {
        delete :destroy, {:id => raw_data_score.to_param}, valid_session
      }.to change(RawDataScore, :count).by(-1)
    end

    it "redirects to the raw_data_scores list" do
      raw_data_score = RawDataScore.create! valid_attributes
      delete :destroy, {:id => raw_data_score.to_param}, valid_session
      response.should redirect_to(raw_data_scores_url)
    end
  end

end
