require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScoreDatesController do

  # This should return the minimal set of attributes required to create a valid
  # ScoreDate. As you add validations to ScoreDate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScoreDatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all score_dates as @score_dates" do
      score_date = ScoreDate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:score_dates).should eq([score_date])
    end
  end

  describe "GET show" do
    it "assigns the requested score_date as @score_date" do
      score_date = ScoreDate.create! valid_attributes
      get :show, {:id => score_date.to_param}, valid_session
      assigns(:score_date).should eq(score_date)
    end
  end

  describe "GET new" do
    it "assigns a new score_date as @score_date" do
      get :new, {}, valid_session
      assigns(:score_date).should be_a_new(ScoreDate)
    end
  end

  describe "GET edit" do
    it "assigns the requested score_date as @score_date" do
      score_date = ScoreDate.create! valid_attributes
      get :edit, {:id => score_date.to_param}, valid_session
      assigns(:score_date).should eq(score_date)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScoreDate" do
        expect {
          post :create, {:score_date => valid_attributes}, valid_session
        }.to change(ScoreDate, :count).by(1)
      end

      it "assigns a newly created score_date as @score_date" do
        post :create, {:score_date => valid_attributes}, valid_session
        assigns(:score_date).should be_a(ScoreDate)
        assigns(:score_date).should be_persisted
      end

      it "redirects to the created score_date" do
        post :create, {:score_date => valid_attributes}, valid_session
        response.should redirect_to(ScoreDate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved score_date as @score_date" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreDate.any_instance.stub(:save).and_return(false)
        post :create, {:score_date => {}}, valid_session
        assigns(:score_date).should be_a_new(ScoreDate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreDate.any_instance.stub(:save).and_return(false)
        post :create, {:score_date => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested score_date" do
        score_date = ScoreDate.create! valid_attributes
        # Assuming there are no other score_dates in the database, this
        # specifies that the ScoreDate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScoreDate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => score_date.to_param, :score_date => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested score_date as @score_date" do
        score_date = ScoreDate.create! valid_attributes
        put :update, {:id => score_date.to_param, :score_date => valid_attributes}, valid_session
        assigns(:score_date).should eq(score_date)
      end

      it "redirects to the score_date" do
        score_date = ScoreDate.create! valid_attributes
        put :update, {:id => score_date.to_param, :score_date => valid_attributes}, valid_session
        response.should redirect_to(score_date)
      end
    end

    describe "with invalid params" do
      it "assigns the score_date as @score_date" do
        score_date = ScoreDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => score_date.to_param, :score_date => {}}, valid_session
        assigns(:score_date).should eq(score_date)
      end

      it "re-renders the 'edit' template" do
        score_date = ScoreDate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreDate.any_instance.stub(:save).and_return(false)
        put :update, {:id => score_date.to_param, :score_date => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested score_date" do
      score_date = ScoreDate.create! valid_attributes
      expect {
        delete :destroy, {:id => score_date.to_param}, valid_session
      }.to change(ScoreDate, :count).by(-1)
    end

    it "redirects to the score_dates list" do
      score_date = ScoreDate.create! valid_attributes
      delete :destroy, {:id => score_date.to_param}, valid_session
      response.should redirect_to(score_dates_url)
    end
  end

end
