require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VectorsController do

  # This should return the minimal set of attributes required to create a valid
  # Vector. As you add validations to Vector, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VectorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all vectors as @vectors" do
      vector = Vector.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vectors).should eq([vector])
    end
  end

  describe "GET show" do
    it "assigns the requested vector as @vector" do
      vector = Vector.create! valid_attributes
      get :show, {:id => vector.to_param}, valid_session
      assigns(:vector).should eq(vector)
    end
  end

  describe "GET new" do
    it "assigns a new vector as @vector" do
      get :new, {}, valid_session
      assigns(:vector).should be_a_new(Vector)
    end
  end

  describe "GET edit" do
    it "assigns the requested vector as @vector" do
      vector = Vector.create! valid_attributes
      get :edit, {:id => vector.to_param}, valid_session
      assigns(:vector).should eq(vector)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vector" do
        expect {
          post :create, {:vector => valid_attributes}, valid_session
        }.to change(Vector, :count).by(1)
      end

      it "assigns a newly created vector as @vector" do
        post :create, {:vector => valid_attributes}, valid_session
        assigns(:vector).should be_a(Vector)
        assigns(:vector).should be_persisted
      end

      it "redirects to the created vector" do
        post :create, {:vector => valid_attributes}, valid_session
        response.should redirect_to(Vector.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vector as @vector" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vector.any_instance.stub(:save).and_return(false)
        post :create, {:vector => {}}, valid_session
        assigns(:vector).should be_a_new(Vector)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vector.any_instance.stub(:save).and_return(false)
        post :create, {:vector => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vector" do
        vector = Vector.create! valid_attributes
        # Assuming there are no other vectors in the database, this
        # specifies that the Vector created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vector.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => vector.to_param, :vector => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested vector as @vector" do
        vector = Vector.create! valid_attributes
        put :update, {:id => vector.to_param, :vector => valid_attributes}, valid_session
        assigns(:vector).should eq(vector)
      end

      it "redirects to the vector" do
        vector = Vector.create! valid_attributes
        put :update, {:id => vector.to_param, :vector => valid_attributes}, valid_session
        response.should redirect_to(vector)
      end
    end

    describe "with invalid params" do
      it "assigns the vector as @vector" do
        vector = Vector.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vector.any_instance.stub(:save).and_return(false)
        put :update, {:id => vector.to_param, :vector => {}}, valid_session
        assigns(:vector).should eq(vector)
      end

      it "re-renders the 'edit' template" do
        vector = Vector.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vector.any_instance.stub(:save).and_return(false)
        put :update, {:id => vector.to_param, :vector => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vector" do
      vector = Vector.create! valid_attributes
      expect {
        delete :destroy, {:id => vector.to_param}, valid_session
      }.to change(Vector, :count).by(-1)
    end

    it "redirects to the vectors list" do
      vector = Vector.create! valid_attributes
      delete :destroy, {:id => vector.to_param}, valid_session
      response.should redirect_to(vectors_url)
    end
  end

end
